### PR TITLE
fix(upgrade): remove tmp files when upgrading

### PR DESCRIPTION
**Pull request by MartinBelthle**
This solves the issue you reported me (tmp files that are not deleted) @laurent-laporte-pro.
The issue was introduced by my last dev to fasten the upgrade.

### CODE REVIEW

**Comment by ghost** [comment]
### Bug Fixes

*  **upgrader:** remove tmp files when upgrading ([cbd5908](https://github.com/AntaresSimulatorTeam/AntaREST/commit/cbd5908876e7a69077ebd865a172164226d274c9))


### Code Refactoring

*  **upgrader:** use `TemporaryDirectory` to manage temp dirs during study upgrade ([343b32d](https://github.com/AntaresSimulatorTeam/AntaREST/commit/343b32d89a5779fac3a9fab15fb0873c7e7fba8b))


### Tests

*  **upgrader:** avoid mixing study dir and temp dir ([4e0e460](https://github.com/AntaresSimulatorTeam/AntaREST/commit/4e0e46015e51aec0f050ce97229b5a905e79792e))


### Contributors

<a href="https://github.com/MartinBelthle">MartinBelthle</a>, <a href="https://github.com/laurent-laporte-pro">laurent-laporte-pro</a>

<details>
<summary>Commit-Lint commands</summary>
<br />

You can trigger Commit-Lint actions by commenting on this PR:
- `@Commit-Lint merge patch` will merge dependabot PR on "patch" versions (X.X.Y - Y change)
- `@Commit-Lint merge minor` will merge dependabot PR on "minor" versions (X.Y.Y - Y change)
- `@Commit-Lint merge major` will merge dependabot PR on "major" versions (Y.Y.Y - Y change)
- `@Commit-Lint merge disable` will desactivate merge dependabot PR
- `@Commit-Lint review` will approve dependabot PR
- `@Commit-Lint stop review` will stop approve dependabot PR



</details>

**Review by laurent-laporte-pro — COMMENTED** [review]
Pour la gestion des répertoires temporaires, il est préférable d'utiliser `tempfile.TemporaryDirectory` qui est un context manager.
Par ailleurs, pour supprimer un fichier avec `pathlib`, on peut utiliser `Path.unlink` (qui possède aussi l'avantage de supprimer les liens symboliques).

**Review by laurent-laporte-pro — APPROVED** [review]
Attention à ne pas mélanger les données de l'étude avec le fichier temporaire contenant un backup de cette même étude.

**Comment by laurent-laporte-pro** [comment]
We should check that a RAW Study is correctly upgraded.
We can also check the Windows version (Desktop)

**Pull request merged**
