### PR TITLE
fix(package): do not create symlink for `AntaresWebServer` during package creation

### PR DESCRIPTION
**Pull request by flomnes**

### CODE REVIEW

**Review by laurent-laporte-pro — DISMISSED** [review]

**Review by laurent-laporte-pro — CHANGES_REQUESTED** [review]
Il faut supprimer le `else`

**Comment by flomnes** [comment]
> Il faut supprimer le `else`

PR vide ?

**Comment by laurent-laporte-pro** [comment]
Creating the symlink is not really necessary, as the user can navigate to the `AntaresWebServer` directory and run the application from there and/or create the symlink themselves. Currently there is a problem with GitHub when creating the ZIP package of the `dist` directory. The ZIP creation is done without preserving symbolic links; instead, the target directory is cloned.

**Review by laurent-laporte-pro — APPROVED** [review]

**Comment by laurent-laporte-pro** [comment]
### Integration Test

On vérifie bien que le package Ubuntu ne contient plus le lien symbolique.

**Pull request merged**
