### PR TITLE
docker-compose: change webapp folder from build to dist

### PR DESCRIPTION
**Pull request by insatomcat**
After building the webapp according to the documentation, the files are in webapp/dist and not in webapp/build

### CODE REVIEW

**Comment by MartinBelthle** [comment]
Not an expert of the front-end but when building the app on my local env I have a folder `webapp/build` and no folder `webapp/dist` so perhaps the doc is wrong ?

**Comment by insatomcat** [comment]
I'm no frontend expert at all...
But the documentation states `IMPORTANT : make sur the generated files are in the dist (or build) folder`
It seems it says "dist" is the preferred version but "build" is still possible (no idea why/how).

But in the end on my setup, it's dist...

```# ls -l dist build/
build/:
total 0
-rwxr-xr-x 1 virtu virtu 0 Jul 22 09:12 config.json

dist:
total 128
drwxr-xr-x 2 root root   4096 Jul 22 11:02 assets
-rwxr-xr-x 1 root root      0 Jul 22 11:03 config.json
-rw-r--r-- 1 root root 103054 Jul 22 11:02 favicon.ico
-rw-r--r-- 1 root root    848 Jul 22 11:02 index.html
drwxr-xr-x 5 root root   4096 Jul 22 11:02 locales
-rw-r--r-- 1 root root   2528 Jul 22 11:02 logo16.png
-rw-r--r-- 1 root root    390 Jul 22 11:02 manifest.json
-rw-r--r-- 1 root root     57 Jul 22 11:02 robots.txt
```

I guess we need to understand which one is the real expected one to know which one should be in the docker-compose file?

**Comment by insatomcat** [comment]
just did it again.

```
virtu@bfe9a08f5ff4:/antares/webapp$ ls build dist
ls: cannot access 'build': No such file or directory
ls: cannot access 'dist': No such file or directory
virtu@bfe9a08f5ff4:/antares/webapp$ npm run build

> antares-web@2.17.3 build
> tsc && vite build

vite v5.0.8 building for production...
[plugin:vite:resolve] Module "stream" has been externalized for browser compatibility, imported by "/antares/webapp/node_modules/sax/lib/sax.js". See https://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.
[plugin:vite:resolve] Module "buffer" has been externalized for browser compatibility, imported by "/antares/webapp/node_modules/string_decoder/node_modules/safe-buffer/index.js". See https://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.
✓ 19422 modules transformed.
dist/index.html                                    0.85 kB │ gzip:     0.46 kB
dist/assets/logo-cU9uk5oQ.png                     10.67 kB
dist/assets/jsoneditor-icons-iJWAtE2N.svg         31.48 kB │ gzip:     5.10 kB
dist/assets/top-right-background-X-XiKvUd.png    119.99 kB
dist/assets/index-w7kR44OO.css                   265.16 kB │ gzip:    43.84 kB
dist/assets/index-yqs8ZfoW.js                  5,828.62 kB │ gzip: 1,677.66 kB

(!) Some chunks are larger than 500 kB after minification. Consider:
- Using dynamic import() to code-split the application
- Use build.rollupOptions.output.manualChunks to improve chunking: https://rollupjs.org/configuration-options/#output-manualchunks
- Adjust chunk size limit for this warning via build.chunkSizeWarningLimit.
✓ built in 31.59s
virtu@bfe9a08f5ff4:/antares/webapp$ ls build dist
ls: cannot access 'build': No such file or directory
dist:
assets  favicon.ico  index.html  locales  logo16.png  manifest.json  robots.txt
virtu@bfe9a08f5ff4:/antares/webapp$
```

**Comment by sylvlecl** [comment]
Indeed the prod build generates files in `dist`, it probably has not been updated when we have switched to vite build system.

**Review by sylvlecl — APPROVED** [review]

**Pull request merged**
