### PR TITLE
build(python): bump project dependencies 

### LINKED ISSUE #1724: Upgrade version of FastAPI and Pydantic
## Problem Statement

The version of FastAPI we are currently using is 0.73, released on 23 January 2022. Although this version is relatively recent, it should be noted that the library is undergoing rapid development within the open-source community. 

This library has dependencies such as Pydantic, Starlette and Requests (used by Starlette). These dependencies also need to be updated to take advantage of new features, bug fixes and security patches.

However, we will not be able to upgrade to version 2 of Pydantic as this would require substantial changes to our code.

Since version 0.21 of Starlette, this library no longer has a dependency on Requests, having replaced it with Httpx, a more modern library. We need to adapt the source code of our application to take account of this change. What's more, given that we use Requests in a very limited and basic way, we can also abandon Requests in favour of Httpx without requiring any considerable effort.

We want to target the following versions:
- FastAPI: 0.103.1
- Httpx: 0.24.1
- Pydantic: 1.10.12
- Starlette: 0.27.0

and drop Requests.

### PR DESCRIPTION
**Pull request by laurent-laporte-pro**
**Martin:**

This PR aims at bumping several project dependencies:
- `pydantic` from 1.9.0 to 2.8.2 :warning: **HUGE** breaking change on their side
- `fastapi` from 0.73.0 to 0.110.3
- `uvicorn` from to 0.15.0 to 0.30.6
- `mypy` from 1.4.1 to 1.11.1

It also brings few changes inside dependencies
- Drop `requests` in favor of `httpx`
- Drop `fastapi-jwt-auth` as they do not and will not support pydantic v2. We've decided to copy their code and adapt it as it's really light (see new folder `/antarest/fastapi_jwt_auth`)

These changes also induced other minor dependencies bump: `jinja2`, `typing_extensions`, `PyJWT`, `python-multipart`

### CODE REVIEW

**Review by flomnes — COMMENTED** [review]
Any documentation about migration ? What deps are you upgrading ? Only FastAPI ?

**Comment by MartinBelthle** [comment]
`fastapi-jwt-auth` doesn't and will not support Pydantic v2 so we have to find another library to do the work ...

**Comment by MartinBelthle** [comment]
Still 85 test failures after commit `use own all optional constructor`

**Comment by MartinBelthle** [comment]
**TODO:** 
After commit `try to fix mpy`:
- Still 45 test failures
- Still 99 mypy issues

**Comment by MartinBelthle** [comment]
**TODO:** 

After commit `24febd1`:
- Still 30 test failures (all inside `integration` folder)
- Still 98 mypy issues

**Comment by MartinBelthle** [comment]
Sonar raises a Security issue concerning the code `Client(verify=False)`.
But this code is only used by the `cli` so I believe we should suppress it.
I'll let you decide @sylvlecl.

**Review by sylvlecl — APPROVED** [review]

**Comment by sylvlecl** [comment]
> Sonar raises a Security issue concerning the code `Client(verify=False)`. But this code is only used by the `cli` so I believe we should suppress it. I'll let you decide @sylvlecl.

For this, although it's in the CLI tool, I preferred to really solve the issue by letting the command line user take the responsibility of disabling SSL certification, through a new argument `--no-verify`.

**Pull request merged**
